export const formList = {
    driving: {
        saved: false,
        isSubmit: true,
        firstName:'',
        secondName:'',
        licenceNumber:'',
        vinNumber:'',
        crimeDate:'',
        fuelType:'',
        dateNational:'',
        dateAccident:'',
        
        isRecentAccident:false,
        country: '',
        state: '',
        zipcode: '',
        interFuelType:'',
        anyIntenationalAccident:false,
        drivingComments: '',
        documents: []
   },
    bodyType: ['BMW', 'Volvo', 'Hundai' , 'Audi'],
    make:['yes' , 'No'],
    milage:['yes' , 'No'],
    fuelType:['Desel' , 'Petrol', 'Gas'],
    intenationalAccident:['Yes','No'],
    fueltypeAccident:['Yes','No'],
    milageAccident:['Yes','No'],
    
    policecase: {
        saved: false,
        isSubmit: true,
        firstName:'',
        secondName:'',
        caseStarton:'',
        caseEndon:'',
        village:'',
        caseYear:'',
        isAnyIssue: false,
        isAnyFir: false,
        isAnyPenalty:false,
        country: '',
        state: '',
        zipcode: '',
        firNumber: '',
        penaltyAmount: '',
        judgementDate: '',
        isImpactcredit:'',
        judgeName: '',
        judementDetails: '',
        isAnyimpact:false,
        policecaseComments: '',
        documents: []
    },
    caseType:['Property', 'Land'],

    localeByCountry: {
        'IN': 'en-IN',
        'US': 'en-US'
    },
    currencyByCountry: {
        'IN': 'INR',
        'US': 'USD'
    },
    

    church: {
        saved: false,
        isSubmit: true,
        firstName:'',
        secondName:'',
        startDate:'',
        endDate:'',
        village:'',
        isAnyIssue: false,
        isAnyFir: false,
        isAnyPenalty:false,
        country: '',
        state: '',
        zipcode: '',
        firNumber: '',
        penaltyAmount: '',
        judgementDate: '',
        judgeName: '',
        judementDetails: '',
        isAnyimpact:false,
        churchComments: '',
        documents: []
    },

    schoolcollege: {
        saved: false,
        isSubmit: true,
        firstName:'',
        secondName:'',
        incidentStarton:'',
        incidentEndon:'',
        schoolvillage:'',
        incidentYear:'',
        isEndissue: false,
        isIssuefir: false,
        isChildCourt: false,
        isIncidentpenalty:false,
       disposition:'',
        country: '',
        state: '',
        zipcode: '',
        firInsnumber: '',
        incidentPenalty: '',
        judgementDate: '',
        judgeName: '',
        incidentJudement: '',
        isAnyimpact:false,
        policecaseComments: '',
        documents: []
    },
    incident:['first','second'],
    disposition:['AAA','BBB'],
     sports: {
        saved: false,
        isSubmit: true,
        firstName:'',
        lastName:'',
        teamName:'',
        sportsStart:'',
        sportsEnd:'',
        sportsLocation:'',
        sportsYear:'',
        isAccidentally: false,
        isRetry: false,
        isOpponent: false,
        isAnyCard:false,
        disposition:'',
        country: '',
        state: '',
        zipcode: '',
        refryName: '',
        opponentTeamName: '',
        numberOfCard: '',
        candidateName: '',
                
        sportsComments: '',
        documents: []
    },
    sportsIncident:['Fell down' , 'Accident'],
    gameCategory:['Indoor' , 'Outdoor'],
    sportsName:['Foot ball' , 'Basket Ball'],
    
    finance: {
        saved: false,
        isSubmit: true,
        firstName:'',
        lastName:'',
        accountNumber:'',
        country: '',
        state: '',
        zipcode: '',
        finStarton:'',
        finEndon:'',
        finLocation:'',
        finDisposition:'',
        finYear:'',
        isBankruptcy: false,
        finRuptcyYear:'',
        finRuptcyDetails:'',
        isFraud:'',
        finFraudYear:'',
        finFraudDetails:'',
        isCheckBounce:false,
        finBounceYear:'',
        finBounceDetails:'',
        isMargageDue: false,
        finMargageYear:'',
        finMargageDetails:'',
        isFine:false,
        finFineYear:'',
        finFineDetails:'',
        financeComments: '',
        documents: []
    },
    financeCrime:['Fake Check' , 'Other Bank Check'],
    bankName:['Canara' , 'ICICI'],
    organizationName:['Holy Cross' , 'St Joseph'],
    sexual: {
        saved: false,
        isSubmit: true,
        isSexualCrime:false,
        isScPublic:false,
        scYear:'',
        scLocation:'',
        scName:'',
        scStartedon:'',
        scEndon:'',
        country: '',
        state: '',
        zipcode: '',
        firstName:'',
        fatherName:'',
        motherName:'',
        lastName:'',
        scDisposition:'',
        scCity:'',
        isScaseFiled: false,
        scaseFiledYear:'',
        scaseDetails:'',
        isSFir:'',
        sFirYear:'',
        sFirDetails:'',
        anyJail:false,
        JailYear:'',
        JailDetails:'',
        anySJudgements: false,
        sJudgementYear:'',
        sJudgementsDetails:'',
        isSHearing:false,
        sHearingYear:'',
        sHearingDetails:'',
        sexualComments: '',
        documents: []
    },    
    
};