export const formList = {
  gparents: {
    saved: false,
    isSubmit: true,
    firstName: '',
    lastName: '',
    dob: '',
    gpBirthlocation: '',
    city: '',
    county: '',
    country: '',
    state: '',
    zipcode: '',
    deathDate: '',
    gpDeathlocation: '',
    isAlive: false,
    gpComments: '',
    documents: [],
  },
  relationship: ['Father', 'Mother', 'Husband', 'Wife'],
  gender: ['Male', 'Female', 'Other'],
  isAlive: ['Yes', 'No'],

  parents: {
    saved: false,
    isSubmit: true,
    dob: '',
    pBirthlocation: '',
    city: '',
    county: '',
    country: '',
    state: '',
    zipcode: '',
    deathDate: '',
    pDeathlocation: '',
    isAlive: false,
    gpComments: '',
    documents: [],
  },
  pRrelationship: ['Father', 'Mother', 'Husband', 'Wife'],
  pGender: ['Male', 'Female', 'Other'],
  isPAlive: ['Yes', 'No'],

  other: {
    saved: false,
    isSubmit: true,
    dob: '',
    locationAddress: '',
    city: '',
    county: '',
    country: '',
    state: '',
    zipcode: '',
    gpComments: '',
    documents: [],
  },
  oRrelationship: ['Father', 'Mother', 'Husband', 'Wife'],
  oGender: ['Male', 'Female', 'Other'],

  spouse: {
    saved: false,
    isSubmit: true,
    sdob: '',
    sBirthlocation: '',
    city: '',
    county: '',
    country: '',
    state: '',
    zipcode: '',
    sdeathDate: '',
    sDeathlocation: '',
    sdeathPlace: '',
    isSAlive: false,
    sComments: '',
    documents: [],
  },
  sRelationship: ['Father', 'Mother', 'Husband', 'Wife'],
  sGender: ['Male', 'Female', 'Other'],
  isSAlive: ['Yes', 'No'],

  child: {
    saved: false,
    isSubmit: true,
    cDob: '',
    cbirthPlace: '',
    locationAddress: '',
    city: '',
    county: '',
    country: '',
    state: '',
    zipcode: '',
    cComments: '',
    documents: [],
  },
  cRelationship: ['Father', 'Mother', 'Husband', 'Wife'],
  cGender: ['Male', 'Female', 'Other'],

  localeByCountry: {
    IN: 'en-IN',
    US: 'en-US',
  },
  currencyByCountry: {
    IN: 'INR',
    US: 'USD',
  },
};
