export const formList = {
  general: {
    saved: false,
    isSubmit: true,
    country: '',
    state: '',
    zipCode: '',
    teamLink: '',
    isMarried: true,
    leagueComments: '',
    documents: [],
  },
 
  gender: ['Male', 'Female', 'Other'],
 

  cashdonation: {
    saved: false,
    isSubmit: true,
    country: '',
    state: '',
    zipCode: '',
    teamLink: '',
    isMarried: true,
    incomeComments: '',
    documents: [],
  },

  localeByCountry: {
    IN: 'en-IN',
    US: 'en-US',
  },
  currencyByCountry: {
    IN: 'INR',
    US: 'USD',
  },

  valuableasset: {
    saved: false,
    isSubmit: true,
    country: '',
    state: '',
    zipCode: '',
    teamLink: '',
    isMarried: true,
    leagueComments: '',
    documents: [],
  },

  kidseducation: {
    saved: false,
    isSubmit: true,
    country: '',
    state: '',
    zipCode: '',
    teamLink: '',
    isMarried: true,
    KidsComments: '',
    documents: [],
  },
  KidsDonate:['Education','Medical'],
  donationType:['Education','Medical'],
  kidsWeekly:['Weekly','Monthly'],

  kinddonation: {
    saved: false,
    isSubmit: true,
    country: '',
    state: '',
    zipCode: '',
    teamLink: '',
    isMarried: true,
    kindonatComments: '',
    documents: [],
  },
  kindItem:['poor','education'],
  labour:['Weekly', 'Daily'],

  globalwarming: {
    saved: false,
    isSubmit: true,    
    country: '',
    state: '',
    zipCode: '',     
    gwarmingComments: '',
    documents: [],
  },
  support:['Grow Plants'],
  globalWarm:['Cutting Tree', 'Reduce Fuel'],

  construction: {
    saved: false,
    isSubmit: true,
    country: '',
    state: '',
    zipCode: '',
    teamLink: '',
    isMarried: true,
    constructComments: '',
    documents: [],
  },
  construct:['weekly amount', 'Daily'],
  constructionType: ['RIBA', 'Prestige', 'Puravankara'],

  stocks: {
    saved: false,
    isSubmit: true,
    country: '',
    state: '',
    zipCode: '',
    teamLink: '',
    isMarried: true,
    stockComments: '',
    documents: [],
  },
  shareName:['Orphanage'],
  stockDonate:['weekly','daily'],

  gifts: {
    saved: false,
    isSubmit: true,
    country: '',
    state: '',
    zipCode: '',
    teamLink: '',
    isMarried: true,
    giftComments: '',
    documents: [],
  },
  giftType: ['Card', 'Gold'],
  giftWeekly:['Weekly','Daily'],

  organs: {
    saved: false,
    isSubmit: true,
    country: '',
    state: '',
    zipCode: '',
    teamLink: '',
    isMarried: true,
    organComments: '',
    documents: [],
  },
  organType:['Eye','Kidney','Heart'],
  bloodGroup:['B+ve','AB+', 'A+', 'B+', 'A-'],

  other: {
    saved: false,
    isSubmit: true,
    country: '',
    state: '',
    zipCode: '',
    teamLink: '',
    isMarried: true,
    leagueComments: '',
    documents: [],
  },
};
