export const formList = {
    public: {
        saved: false,
        isSubmit: true,        
        pubOrgName:'',
        pubGroupSince:'',
        pubMemberSince:'',
        pubNumberMember:'',
        country: '',
        state: '',
        zipcode: '',
        isPublic: false,
        isPubBoardMember:false,
        pubNumYears:'',
        publicComments: '',
        documents: []
   },
   pubGroupName: ['ABC', 'Reliance'],
   pubGroupType:['NLC', 'Lakshmi'],
   pubPosition:['VP' , 'MD'],
      
    private: {
        saved: false,
        isSubmit: true,        
        privOrgName:'',
        privGroupSince:'',
        privMemberSince:'',
        privNumberMember:'',
        country: '',
        state: '',
        zipcode: '',
        isPrivate: false,
        isPrivBoardMember:false,
        privNumYears:'',
        privComments: '',
        documents: []
   },
    privGroupName: ['ABC', 'Reliance'],
    privGroupType:['NLC', 'Lakshmi'],
    privPosition:['VP' , 'MD'],

    localeByCountry: {
        'IN': 'en-IN',
        'US': 'en-US'
    },
    currencyByCountry: {
        'IN': 'INR',
        'US': 'USD'
    },
    

    volunteer: {
        saved: false,
        isSubmit: true,        
        volunOrgName:'',
        volunGroupSince:'',
        volunMemberSince:'',
        volunNumberMember:'',
        country: '',
        state: '',
        zipcode: '',
        isVolunteer: false,
        isVolunBoardMember:false,
        volunNumYears:'',
        volunComments: '',
        documents: []
    },
    volunGroupName: ['ABC', 'Reliance'],
    volunGroupType:['NLC', 'Lakshmi'],
    volunPosition:['VP' , 'MD'],
    
     sports: {
        saved: false,
        isSubmit: true,        
        sportOrgName:'',
        sportGroupSince:'',
        sportMemberSince:'',
        sportNumberMember:'',
        country: '',
        state: '',
        zipcode: '',
        isSports: false,
        isSportBoardMember:false,
        sportNumYears:'',
        sportComments: '',
        documents: []
    },
    sportGroupName: ['ABC', 'Reliance'],
    sportGroupType:['NLC', 'Lakshmi'],
    sportPosition:['VP' , 'MD'],
    
    media: {
        saved: false,
        isSubmit: true,        
        mediaOrgName:'',
        mediaGroupSince:'',
        mediaMemberSince:'',
        mediaNumberMember:'',
        country: '',
        state: '',
        zipcode: '',
        isMedia: false,
        isMediaBoardMember:false,
        mediaNumYears:'',
        mediaComments: '',
        documents: []
    },
    mediaGroupName: ['ABC', 'Reliance'],
    mediaGroupType:['NLC', 'Lakshmi'],
    mediaPosition:['VP' , 'MD'],
    
    social: {
        saved: false,
        isSubmit: true,        
        socialOrgName:'',
        socialGroupSince:'',
        socialMemberSince:'',
        socialNumberMember:'',
        country: '',
        state: '',
        zipcode: '',
        isSocial: false,
        isSocialBoardMember:false,
        socialNumYears:'',
        socialComments: '',
        documents: []
    },
    socialGroupName: ['ABC', 'Reliance'],
    socialGroupType:['NLC', 'Lakshmi'],
    socialPosition:['VP' , 'MD'],

    security: {
        saved: false,
        isSubmit: true,        
        securOrgName:'',
        securGroupSince:'',
        securMemberSince:'',
        securNumberMember:'',
        country: '',
        state: '',
        zipcode: '',
        isSecurity: false,
        isSecurBoardMember:false,
        securNumYears:'',
        securComments: '',
        documents: []
    },
    securGroupName: ['ABC', 'Reliance'],
    securGroupType:['NLC', 'Lakshmi'],
    securPosition:['VP' , 'MD'],

    gaming: {
        saved: false,
        isSubmit: true,        
        gameOrgName:'',
        gameGroupSince:'',
        gameMemberSince:'',
        gameNumberMember:'',
        country: '',
        state: '',
        zipcode: '',
        isGaming: false,
        isGameBoardMember:false,
        gameNumYears:'',
        gameComments: '',
        documents: []
    },
    gameGroupName: ['ABC', 'Reliance'],
    gameGroupType:['NLC', 'Lakshmi'],
    gamePosition:['VP' , 'MD'],

    research: {
        saved: false,
        isSubmit: true,        
        researchOrgName:'',
        researchGroupSince:'',
        researchMemberSince:'',
        researchNumberMember:'',
        country: '',
        state: '',
        zipcode: '',
        isResearch: false,
        isRdBoardMember:false,
        anyResearch:false,
        researchNumYears:'',
        researchComments: '',
        documents: []
    },
    researchGroupName: ['ABC', 'Reliance'],
    researchGroupType:['NLC', 'Lakshmi'],
    researchPosition:['VP' , 'MD'],

    finance: {
        saved: false,
        isSubmit: true,        
        finOrgName:'',
        finGroupSince:'',
        finMemberSince:'',
        finNumberMember:'',
        country: '',
        state: '',
        zipcode: '',
        isFinance: false,
        isFinBoardMember:false,
        isCa:false,
        finNumYears:'',
        finComments: '',
        documents: []
    },
    finGroupName: ['ABC', 'Reliance'],
    finGroupType:['NLC', 'Lakshmi'],
    finPosition:['VP' , 'MD'],


    community: {
        saved: false,
        isSubmit: true,        
        comOrgName:'',
        comGroupSince:'',
        comMemberSince:'',
        comNumberMember:'',
        country: '',
        state: '',
        zipcode: '',
        isCommunity: false,
        iscomBoardMember:false,
        comNumYears:'',
        comComments: '',
        documents: []
    },
    comGroupName: ['ABC', 'Reliance'],
    comGroupType:['NLC', 'Lakshmi'],
    comPosition:['VP' , 'MD'],

    construction: {
        saved: false,
        isSubmit: true,        
        constOrgName:'',
        constGroupSince:'',
        constMemberSince:'',
        constNumberMember:'',
        country: '',
        state: '',
        zipcode: '',
        isConstruction: false,
        isConstBoardMember:false,
        constNumYears:'',
        constComments: '',
        documents: []
    },    
    constGroupName: ['ABC', 'Reliance'],
    constGroupType:['NLC', 'Lakshmi'],
    constPosition:['VP' , 'MD'],
    constType: ['ABC', 'Reliance'],

    
};