export const formList = {
  general: {
    saved: false,
    isSubmit: true,
    country: '',
    state: '',
    zipcode: '',
    teamLink: '',
    isMarried: true,
    generalComments: '',
    documents: [],
  },
  relationship: ['Son', 'Spouse', 'Daughter', 'Appa', 'Amma'],
  gender: ['Male', 'Female', 'Other'],
  isHousehold: ['Yes', 'No'],

  income: {
    saved: false,
    isSubmit: true,
    country: '',
    state: '',
    zipcode: '',
    teamLink: '',
    isMarried: true,
    incomeComments: '',
    documents: [],
  },

  localeByCountry: {
    IN: 'en-IN',
    US: 'en-US',
  },
  currencyByCountry: {
    IN: 'INR',
    US: 'USD',
  },

  family: {
    saved: false,
    isSubmit: true,
    country: '',
    state: '',
    zipcode: '',
    teamLink: '',
    isMarried: true,
    familyComments: '',
    documents: [],
  },

  oincome: {
    saved: false,
    isSubmit: true,
    country: '',
    state: '',
    zipcode: '',
    teamLink: '',
    isMarried: true,
    oincomeComments: '',
    documents: [],
  },

  education: {
    saved: false,
    isSubmit: true,
    country: '',
    state: '',
    zipcode: '',
    teamLink: '',
    isMarried: true,
    educationComments: '',
    documents: [],
  },

  retirement: {
    saved: false,
    isSubmit: true,
    country: '',
    state: '',
    zipcode: '',
    retirementComments: '',
    documents: [],
  },

  odeductions: {
    saved: false,
    isSubmit: true,
    country: '',
    state: '',
    zipcode: '',
    teamLink: '',
    isMarried: true,
    odeductionsComments: '',
    documents: [],
  },

  home: {
    saved: false,
    isSubmit: true,
    country: '',
    state: '',
    zipcode: '',
    teamLink: '',
    isMarried: true,
    homeComments: '',
    documents: [],
  },

  selfemploy: {
    saved: false,
    isSubmit: true,
    country: '',
    state: '',
    zipcode: '',
    teamLink: '',
    isMarried: true,
    selfemployComments: '',
    documents: [],
  },

  taxpay: {
    saved: false,
    isSubmit: true,
    country: '',
    state: '',
    zipcode: '',
    teamLink: '',
    isMarried: true,
    taxpayComments: '',
    documents: [],
  },
  donation: {
    saved: false,
    isSubmit: true,
    country: '',
    state: '',
    zipcode: '',
    teamLink: '',
    isMarried: true,
    donationComments: '',
    documents: [],
  },
};
