export const formList = {
  onlinesave: {
    saved: false,
    isSubmit: true,
    country: '',
    state: '',
    zipCode: '',
    teamLink: '',
    isMarried: true,
    onlinesaveComments: '',
    documents: [],
  },
  accountType: ['RD', 'Fixed'],
  relationship: ['Son', 'Spouse', 'Daughter', 'Appa', 'Amma'],
  gender: ['Male', 'Female', 'Other'],
  isHousehold: ['Yes', 'No'],

  studentsave: {
    saved: false,
    isSubmit: true,
    country: '',
    state: '',
    zipCode: '',
    teamLink: '',
    isMarried: true,
    studentsaveComments: '',
    documents: [],
  },
  planType: ['LIC', 'Gold Plan'],

  localeByCountry: {
    IN: 'en-IN',
    US: 'en-US',
  },
  currencyByCountry: {
    IN: 'INR',
    US: 'USD',
  },

  certifysave: {
    saved: false,
    isSubmit: true,
    country: '',
    state: '',
    zipCode: '',
    teamLink: '',
    isMarried: true,
    certifysaveComments: '',
    documents: [],
  },
  cdplanType: ['Fixed', 'RD'],
  moneymarket: {
    saved: false,
    isSubmit: true,
    country: '',
    state: '',
    zipCode: '',
    teamLink: '',
    isMarried: true,
    moneymarketComments: '',
    documents: [],
  },
  mmplanType: ['RD', 'Fixed'],

  tradingonline: {
    saved: false,
    isSubmit: true,
    country: '',
    state: '',
    zipCode: '',
    teamLink: '',
    isMarried: true,
    tradingonlineComments: '',
    documents: [],
  },
  tradeType: ['RD', 'Fixed'],

  healthsave: {
    saved: false,
    isSubmit: true,
    country: '',
    state: '',
    zipCode: '',
    teamLink: '',
    isMarried: true,
    healthsaveComments: '',
    documents: [],
  },
  hsaName:['anual','Monthly'],

  irasaving: {
    saved: false,
    isSubmit: true,
    country: '',
    state: '',
    zipCode: '',
    teamLink: '',
    isMarried: true,
    irasavingComments: '',
    documents: [],
  },
  iraAccount:['Monthly','Yearly'],
  constructionType: ['RIBA', 'Prestige', 'Puravankara'],

  investmentsave: {
    saved: false,
    isSubmit: true,
    country: '',
    state: '',
    zipCode: '',
    teamLink: '',
    isMarried: true,
    leagueComments: '',
    documents: [],
  },

  insurancesave: {
    saved: false,
    isSubmit: true,
    country: '',
    state: '',
    zipCode: '',
    teamLink: '',
    isMarried: true,
    insurancesaveComments: '',
    documents: [],
  },
  giftType: ['Card', 'Gold'],
};
