export const formList = {
  league: {
    saved: false,
    isSubmit: true,
    country: '',
    state: '',
    zipCode: '',
    teamLink: '',
    isRecentleague: true,
    leagueComments: '',
    documents: [],
  },
  sportsName: ['Soccor', 'Cricker'],
  sportsType: ['Indoor', 'Outdoor'],
  clubName: ['FEPYC', 'YSMAN'],

  localeByCountry: {
    IN: 'en-IN',
    US: 'ens-US',
  },
  currencyByCountry: {
    IN: 'INR',
    US: 'USD',
  },

  domestic: {
    saved: false,
    isSubmit: true,
    country: '',
    state: '',
    zipCode: '',
    teamLink: '',
    isRecentPersonal: true,
    domesticComments: '',
    documents: [],
  },
  stateTeam: ['yes', 'No'],
  international: {
    saved: false,
    isSubmit: true,
    country: '',
    state: '',
    zipCode: '',
    teamLink: '',
    isRecentINational: true,
    iNationalComments: '',
    documents: [],
  },

  awards: {
    saved: false,
    isSubmit: true,
    country: '',
    state: '',
    zipCode: '',
    teamLink: '',
    participent: '',
    partNo: '',
    isRecentAwards: true,
    awardsComments: '',
    documents: [],
  },
 
  participent: [
    'Participent',
    'Runner',
    'Winner',
    'StateRunner',
    'StateWinner',
    'National Runner',
    'International Runner',
    'National Winner',
    'InterNational Winner',
    'Olymbic',
  ],

  gameLevel: ['County', 'state', 'National'],
  rank: {
    saved: false,
    isSubmit: true,
    country: '',
    state: '',
    zipCode: '',
    teamLink: '',
    participent: '',
    isRecentRank: true,
    rankComments: '',
    documents: [],
  },
};
