export const formList = {
  billing: {
    saved: false,
    isSubmit: true,
    billType: '',
    shopName: '',
    invoiceNumber: '',
    paymentDate: '',
    cardNumber: '',
    cardNumber: '',
    address: '',
    county: '',
    city: '',
    country: '',
    state: '',
    zipCode: '',
    billMonth: '',
    billYear: '',
    billAmount: '',
    isGwhoamiAccount: false,
    billingComments: '',
    documents: [],
  },
  paymentType: ['Credit card', 'Master Card', 'Debit', ''],
  billType: ['Grocery', 'Medical'],
  paymentto: {
    saved: false,
    isSubmit: true,
    pShopName: '',
    pInvoiceNumber: '',
    pPaymentDate: '',
    pAddress: '',
    pCardNumber: '',
    pCity: '',
    pCounty: '',
    country: '',
    state: '',
    zipCode: '',
    paymentMonth: '',
    paymentYear: '',
    paymentAmount: '',
    ispGwhoamiAccount: false,
    paymentComments: '',
    documents: [],
  },
  paymentType: ['Credit card', 'Master Card', 'Debit', ''],
  itemType: ['Medicine', 'Grocery'],

  localeByCountry: {
    IN: 'en-IN',
    US: 'en-US',
  },
  currencyByCountry: {
    IN: 'INR',
    US: 'USD',
  },

  test: {
    saved: false,
    isSubmit: true,
    billType: '',
    shopName: '',
    invoiceNumber: '',
    paymentDate: '',
    locationAddress: '',
    cardNumber: '',
    city: '',
    county: '',
    country: '',
    state: '',
    zipcode: '',
    billMonth: '',
    billYear: '',
    billAmount: '',
    isGwhoamiAccount: false,
    testComments: '',
    documents: [],
  },
};
